global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: torus
    scheme: https

    static_configs:
      - targets:
          - torus:8443

    tls_config:
      insecure_skip_verify: true
